sudo: required
services:
  - docker

before_install:
  - docker build -t mikaelbeat/docker_training/frontend -f Dockerfile.dev .

script:
  - docker run -e CI=true mikaelbeat/docker_training/frontend npm run test